from random import choice
import pygame as pg
from math import sqrt, pi

# SCREEN SIZE
Y_SIZE = HEIGHT = 700
X_SIZE = WIDTH = 1000
size = [WIDTH, HEIGHT]
HALF_HEIGHT = HEIGHT / 2
HALF_WIDTH = WIDTH / 2

# COLORS
BG_COLOR = 'black'

# SNAKE
SNAKE_DEFAULT_COLOR = 'green'
SNAKE_TILE = 50
SNAKE_MOVE_TIMEOUT = 0.8

# FONTS
FIRST_LINE_SPACE = 10
NUMBER_OF_OTHER_PLAYERS = 79
DEFAULT_FONT_SIZE = 50
FONT_HEIGHT_SPACE = 30





